### ISSUE TITLE
Multiple URIs in the field of "URL of data online" in the census

### ISSUE THREAD

**Issue by jgkim** [okfn/opendatacensus#685] opened 2015-09-10 07:04 UTC
Sometimes people need to input multiple URIs to the field of "URL of data online." In [my case](http://global.census.okfn.org/submission/de3d1e14-7a56-440d-b03a-40fc385de957?post_submission=/submission/de3d1e14-7a56-440d-b03a-40fc385de957), for the health performance category, the required datasets are provided by two different organizations so URLs of data online is two different ones. However, the census requires only one appropriate URI. I've just concatenated the two URLs into one with "&," but we need to fix the code to support this situation. There would be another field with the same problem (i.e. the field of "URL to license or terms of use").

**Comment by pwalsh** [comment] 2015-09-10 07:09
Hi @jgkim 

This has been talked about before, and decided that it is not worth adding tot he code at this stage for the benefit it provides in a subset of cases. 

Suggestion: this should be taken up in the forum (https://discuss.okfn.org/c/open-data-index) with @morchickit and @nealbastek - if they prioritize it, we can then look from there at the possibility of implementation.

For now, I'm closing the issue as it is not a bug and in order to introduce as a feature, it would require discussion here: https://discuss.okfn.org/c/open-data-index

**Closed by pwalsh** 2015-09-10 07:09 UTC
Labels: question, wontfix

**Comment by jgkim** [comment] 2015-09-10 07:11
Thanks @pwalsh.

I've already posted a topic on the forum: https://discuss.okfn.org/t/multiple-uris-in-the-field-of-url-of-data-online-in-the-census/1143
