### ISSUE TITLE
Update Census for 2016

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#735] opened 2016-01-05 07:20 UTC
On [Australia's Regional Open Data Census](http://australia.census.okfn.org)

- Change log is blank
- Previous 2015 submissions that were not assessed have gone 
- cannot add new submissions

Others having the [similar issues](https://discuss.okfn.org/t/unable-to-review-2015-submissions/1731).

Suspect this is due to to us now being in 2016 - Happy New Year  ;-)

**Comment by pwalsh** [comment] 2016-01-05 07:28
@Stephen-Gates if you have any other specific pointers, it can be great (e.g.: URL to a pending submission that no longer appears).

@morchickit also if you can provide more info. Here is a dump of what you emailed me:

1. Noticed same issue on http://cl-city.census.okfn.org/
2. Noticed same issue on http://sciencepo.census.okfn.org/ and we have a particular URL to help, where this is a pending submission - http://sciencepo.census.okfn.org/submission/82a7c795-541c-48ef-b23c-64dc3d2fc34c - which can no longer be found in the UI

@borysyuk this is definitely an issue with all the tricky filters and processors to display data for each year.  I recommend starting by inspecting the database directly for records, and then looking at how and why they are being filtered out now that we moved to a new year.

Points of interest in the code:

* https://github.com/okfn/opendatacensus/blob/develop/census/app.js#L38
* https://github.com/okfn/opendatacensus/blob/develop/census/models/utils.js#L181

**Comment by Stephen-Gates** [comment] 2016-01-05 07:30
@pwalsh I believe I had one outstanding submission on http://australia.census.okfn.org/entry/qld/contracts

**Comment by pwalsh** [comment] 2016-01-05 07:34
Thanks @Stephen-Gates  - we are on it :)

**Comment by Stephen-Gates** [comment] 2016-01-05 08:23
2016 now appears on the home page and I have [successfully added](http://australia.census.okfn.org/changes/) a 2016 submission that was automatically accepted. 

I didn't realise that `approve_first_submission` applied to the start of each year - @pwalsh is that the intended functionality?

**Comment by pwalsh** [comment] 2016-01-05 08:24
yes it is intended functionality. If it is not *desirable* as a census owner, please open it as a distinct issue though. 2016 appeared now because I added it, but it is not directly related to the bug in this issue - I just added it when I did some initial investigation.

**Comment by borysyuk** [comment] 2016-01-05 18:03
There is no bug because pages : 
http://cl-city.census.okfn.org/changes/
http://cl-city.census.okfn.org/
http://cl-city.census.okfn.org/place/iquique and etc
these pages always show `pending submissions` and etc for current year only.

if you want see information about submission for previous years you should use urls: 
http://cl-city.census.okfn.org/changes/2015/
http://cl-city.census.okfn.org/year/2015/
http://cl-city.census.okfn.org/place/iquique/2015/ and etc

**Comment by ponentesincausa** [comment] 2016-01-05 18:16
@borysyuk I am using those links, in my case http://mx-city.census.okfn.org/changes/2015/ but the review button simply does not appear on the entries. Neither for myself (reviewer) for the admin.

**Comment by ponentesincausa** [comment] 2016-01-05 18:19
@borysyuk @Stephen-Gates you know what? I think you are right, these are 2 different issues. We can see 2015 submissions on mx-city, we are just unable to review them due to a lack of Review button.

**Comment by pwalsh** [comment] 2016-01-05 18:24
@morchickit 

( cc @ponentesincausa @Stephen-Gates  )

When the census was refactored, we made w decision (in consultation with Mor and other from non-technical side) to automate the previously manual task of changing over a census per year. 

When it was manual it led to various data bugs when census admins would forget to shift the year as the new year came in, so that would mean records collected in one year and recorded against a different one.

So, based on the current logic, each new year cleans the slate for the census, and you **can't make canes for previous years** - which obviously includes pending entries.

So, this is not a bug, it was the design, based on the pattern of census data being grouped by calendar year. It means that when the year ended, the census collection ended for that year, and therefore pending entries are considered "stale", and we expect new ones for the new census year.

We can make changes to some of this logic of course, but this was the design, and @borysyuk did a deep dive on the code again today to confirm this behaviour.

**Comment by tlacoyodefrijol** [comment] 2016-01-05 18:35
https://media.giphy.com/media/lNHMPbRz6IhKU/giphy.gif

**Comment by tlacoyodefrijol** [comment] 2016-01-05 18:36
![image](https://media.giphy.com/media/lNHMPbRz6IhKU/giphy.gif)

**Comment by Stephen-Gates** [comment] 2016-01-05 19:54
@borysyuk @pwalsh Thanks for looking into the issue. I have updated the [FAQ](http://australia.census.okfn.org/faq/#year) on the Australian Census to reflect the behaviour. I think the behaviour should be also documented at http://census.okfn.org/site-admins/ so Site Admins can be aware and add the information to their FAQ or Tutorial page (thoughts?).

One last question, shouldn't 2016 automatically been added to the home page based on the current date? Or is this a manual Sys Admin task each year?  My FAQ says, "the census closes on 31 Dec" but does it really change when the Sys Admin adds the new year?

**Comment by pwalsh** [comment] 2016-01-05 19:59
@Stephen-Gates the missing year navigation on the home page was just some pure laziness on my behalf, as the [HTML snippet is manual](https://github.com/okfn/opendatacensus/blob/develop/census/views/_snippets/year_navigation.html#L2), and not auto-generated based on the year and year range. It is a pretty simple fix.

More generally though, Are you ok with this behaviour Stephen or do you think it would be preferable to "bring forward" pending entries? Bringing forward seems simple at first, but actually, it would have a serious effect on the UX of the new overview page - we'd lose the calls to action where each year the census looks empty again and needs to be filled, which was a major UX change we did here several months back.

**Comment by Stephen-Gates** [comment] 2016-01-05 20:07
@pwalsh I'm OK with the behaviour now that I understand it. It's not only a call to action for contributors but also to editors to do their reviews by the end of the year. Luckily I only had one outstanding submission and given I now know how to access it I can arrange re-submission.

Happy to close this issue if others are.

**Comment by morchickit** [comment] 2016-01-05 23:35
Hi!
Not happy to close this issue. While I understand the logic, it is
problematic for some instances (not all!), which were taking part in the
local Index Sprint that we did.
Paul, is there a way to write a script and push some instances data forward?
Not ideal, but will save a lot of manual work for some instances.

**Comment by pwalsh** [comment] 2016-01-06 06:46
@morchickit I'll talk with you today about it, but I strongly suggest you update the docs and communication with community to make it clear that the census is calendar year based (which while it seems clear because the whole UI is around calendar year, obviously needs to be made much more explicit), so that this info is clear and accessible for census admins and users.

**Comment by morchickit** [comment] 2016-01-06 10:58
+1 to update the docs. I'll take this on me.

**Comment by pwalsh** [comment] 2016-01-06 11:12
I'm closing this issue now as it is not a bug. I'm opening a new issue to modify data for the handful of census instances that are currently doing a data collection that unfortunately spans across a calendar year: https://github.com/okfn/opendatacensus/issues/738

**Closed by pwalsh** 2016-01-06 11:12 UTC
Labels: bug

**Comment by pwalsh** [comment] 2016-01-06 15:40
See #738

**Comment by wfdd** [comment] 2016-01-25 20:00
This would've made more sense if old-ish submissions had been reviewed before the new year.  If your submissions hadn't been reviewed for three months and then they were to simply vanish, you'd be a little disheartened.

**Comment by pwalsh** [comment] 2016-01-26 04:16
Hi @wfdd 

This issue was closed 3 weeks ago. If you run a local census and this issue effected your entries, or if you have some other problem, can you please open a new issue on the problem.

From your comment, I'm not sure what you are trying to say: if submissions had been *reviewed*, then there would be no issue at all, the only submissions that go missing from the UI as a calendar year changes are the unreviewed ones.

**Comment by wfdd** [comment] 2016-01-26 11:07
Sorry, I should've been clearer; I was referring to global OKFN census.  Take [Cyprus](http://global.census.okfn.org/place/cy): there had been four changes under review - which we'd simply have to verify as correct in the new year - but all four have now been wiped.   I feel contributors should at least be warned of the impending database reset.

**Comment by pwalsh** [comment] 2016-01-26 11:11
@wfdd agree contributors should be warned in general, and @morchickit is working on better messaging for that on local censuses. For the Global one, I thought it has always been very clear that it is calendar year based, but we'll make an effort to clarify that too.
